### ISSUE TITLE
"Undefined index: access_token" on $data['access_token']

### ISSUE THREAD

**Issue by samsonong** [getgrav/grav-plugin-login-oauth#14]
Hi everyone,

I'm having problems with Facebook Login function for this plugin.

Non-logged in users goes to /login > clicks on Facebook button > signs in as Facebook User > encounters error

Anyone have any clue what's driving the error?

Warmest Regards,
Samson

**Comment by happywebkk** [comment]
Hi!

I had the same issue. I found a solution here:
https://github.com/artdarek/oauth-4-laravel/issues/174

You need to change line 162 of the file vendor/lusitanian/oauth/src/OAuth/OAuth2/Service/Facebook.php

Replace:
parse_str($responseBody, $data);
By:
$data = json_decode($responseBody, true);

Good luck (-:

**Comment by Vivalldi** [comment]
@thomasporhel thank you for bringing this issue back to life. It would seem that Lusitanian/PHPoAuthLib v0.8.10 addresses this issue. Will be updating our vendor shortly.

**Comment by Vivalldi** [comment]
Fixed in version 1.4.0
