### ISSUE TITLE
Can this be used with the admin panel for staff to login with?

### ISSUE THREAD

**Issue by ryanapil** [getgrav/grav-plugin-login-oauth#15]

**Comment by flaviocopes** [comment]
No, currently this is a frontend-only plugin

**Comment by jimblue** [comment]
@flaviocopes can we change this for feature request and reopen this issue? thanks

**Comment by drzraf** [comment]
This should be made explicit in the README that this plugin **does not** handle administration.

**Comment by rhukster** [comment]
This is deprecated in favor of https://github.com/trilbymedia/grav-plugin-login-oauth2
