### ISSUE TITLE
Feature: Google Authentication with Domain Filtering

### ISSUE THREAD

**Issue by cd13sr** [getgrav/grav-plugin-login-oauth#5]
I would love to see domain filtering with Google Authentication.

Just thinking out loud here. Using regular expressions (or something more intuitive) to filter against the domain name or email address. For example, user@example.com would filter against "example.com".

The ability to specify Domain Whitelist and Domain Blacklist regex lists.

Also, LDAP/Active Directory Authentication would be awesome as well.

Thanks, looking forward to this!

**Comment by Vivalldi** [comment]
@cd13sr what exactly do you mean by domain filtering? Like only allowing users with a certain email domain through?

LDAP is currently being worked on independently as though they haven't added to GPM yet. https://hub.devdot.io/grav/login-ldap

**Comment by cd13sr** [comment]
Yep. And the ability to allow one or many domains through would be great. For example:
- Let's say I own example.com and sample.org
- Only the people with an example.com or sample.org email address could login
- All other email addresses that do not match those domains would be blocked

Thanks for the LDAP note.

**Comment by b0Stark** [comment]
@Vivalldi Any hint about when this would be available?

**Comment by Vivalldi** [comment]
@b0Stark I have a time blocked off for it this coming Sunday in the evening. I'll advise you once I know more

**Comment by b0Stark** [comment]
@Vivalldi, Thank you for the quick response. I am looking through the code as well to see if I can make sense out of this. It has become clear to me that I have not properly touched PHP in far too long. Again, thank you for having a look at this. :) Much appreciated.

**Comment by Vivalldi** [comment]
Yeah, from what I have seen briefly I'll need to add a custom header to the lusitanian library. Stay tuned 👍

**Comment by ahmadassaf** [comment]
any progress on this guys ? looking forward to have it implemented

**Comment by Vivalldi** [comment]
Sorry for the huge delay everyone. This got put on the back burner for quite sometime. Will be in 1.3.0

**Comment by ganar** [comment]
I'm sorry for reopening this issue: is there a way to know if this got into the code?

**Comment by w00fz** [comment]
This plugin is not maintained anymore - you should checkout https://github.com/trilbymedia/grav-plugin-login-oauth2 which supports OAuth2
